# Generated by Django 5.2.15 on 2026-06-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0003_storedfile_content_family_storedfile_detected_mime_and_more"),
        ("knowledge", "0004_wiki_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="kbdocument",
            name="detected_family",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="kbdocument",
            name="detected_mime",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="kbdocument",
            name="failure_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="kbdocument",
            name="parser_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="kbdocument",
            name="parser_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="ContentExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "可入库"),
                            ("failed", "抽取失败"),
                            ("unsupported", "不支持"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("langchain_loader", "LangChain Loader"),
                            ("text_fallback", "文本容错解析"),
                            ("html_fallback", "HTML 容错解析"),
                            ("vision_model", "视觉模型解析"),
                            ("unsupported", "不支持"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=128)),
                ("raw_output", models.TextField(blank=True)),
                ("normalized_text", models.TextField(blank=True)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_extractions",
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "user_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drive.userfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="kbdocument",
            name="extraction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="knowledge.contentextraction",
            ),
        ),
        migrations.AddIndex(
            model_name="contentextraction",
            index=models.Index(
                fields=["kb", "user_file", "status"],
                name="knowledge_c_kb_user_f44c89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentextraction",
            index=models.Index(
                fields=["failure_code"], name="knowledge_c_failure_0e11d4_idx"
            ),
        ),
    ]
