from django.urls import path, re_path

from . import views


urlpatterns = [
    path("auth/register", views.auth_register),
    path("auth/register-by-invite", views.auth_register),
    path("auth/invitations/lookup", lambda request: views.ok({"valid": False})),
    path("auth/login", views.auth_login),
    path("auth/auto-setup", views.auth_auto_setup),
    path("auth/config", views.auth_config),
    path("auth/switch-tenant", views.switch_tenant),
    path("auth/oidc/config", views.oidc_config),
    path("auth/oidc/url", views.oidc_url),
    path("auth/oidc/callback", views.oidc_callback),
    path("auth/refresh", views.auth_refresh),
    path("auth/validate", views.auth_validate),
    path("auth/logout", views.auth_logout),
    path("auth/me", views.auth_me),
    path("auth/me/preferences", views.auth_preferences),
    path("auth/change-password", views.auth_change_password),
    path("tenants", views.tenants_collection),
    path("tenants/all", views.tenants_collection),
    path("tenants/search", views.tenants_collection),
    path("tenants/kv/<str:key>", views.tenant_kv),
    path("tenants/<int:tenant_id>", views.tenant_detail),
    path("tenants/<int:tenant_id>/api-key", views.tenant_api_key),
    path("tenants/<int:tenant_id>/members", views.tenant_members),
    path("tenants/<int:tenant_id>/members/<str:user_id>", views.tenant_members),
    path("tenants/<int:tenant_id>/leave", views.generic_action, {"resource_type": "tenants", "action": "leave"}),
    path("tenants/<int:tenant_id>/invitations", views.generic_collection, {"resource_type": "tenant_invitations"}),
    path("tenants/<int:tenant_id>/invite-links", views.generic_action, {"resource_type": "tenant_invitations", "action": "invite-links"}),
    path("tenants/<int:tenant_id>/audit-log", views.audit_logs),
    path("me/invitations", views.generic_collection, {"resource_type": "my_invitations"}),
    path("me/invitations/pending-count", lambda request: views.ok({"count": 0})),
    path("me/invitations/<str:item_id>/accept", views.generic_action, {"resource_type": "my_invitations", "action": "accept"}),
    path("me/invitations/<str:item_id>/decline", views.generic_action, {"resource_type": "my_invitations", "action": "decline"}),
    path("knowledge-bases", views.knowledge_bases),
    path("knowledge-bases/copy", views.kb_copy),
    path("knowledge-bases/copy/progress/<str:task_id>", views.task_progress),
    path("knowledge-bases/<str:kb_id>", views.knowledge_bases),
    path("knowledge-bases/<str:kb_id>/pin", views.kb_pin),
    path("knowledge-bases/<str:kb_id>/hybrid-search", views.kb_hybrid_search),
    path("knowledge-bases/<str:kb_id>/move-targets", views.kb_move_targets),
    path("knowledge-bases/<str:kb_id>/knowledge/stats", views.knowledge_stats),
    path("knowledge-bases/<str:kb_id>/knowledge", views.knowledge_collection),
    path("knowledge-bases/<str:kb_id>/knowledge/batch-delete", views.knowledge_batch_delete),
    path("knowledge-bases/<str:kb_id>/knowledge/move", views.knowledge_move),
    path("knowledge-bases/<str:kb_id>/knowledge/file", views.knowledge_file),
    path("knowledge-bases/<str:kb_id>/tags", views.tags_collection),
    path("knowledge-bases/<str:kb_id>/tags/<str:tag_id>", views.tags_collection),
    path("knowledge/batch", views.knowledge_batch),
    path("knowledge/search", views.knowledge_search),
    path("knowledge/batch-delete", views.knowledge_batch_delete),
    path("knowledge/move", views.knowledge_move),
    path("knowledge/move/progress/<str:task_id>", views.task_progress),
    path("knowledge/<str:knowledge_id>", views.knowledge_detail),
    path("knowledge/<str:knowledge_id>/stages", views.knowledge_spans),
    path("knowledge/<str:knowledge_id>/spans", views.knowledge_spans),
    path("knowledge/<str:knowledge_id>/reparse", views.knowledge_reparse),
    path("knowledge/<str:knowledge_id>/cancel-parse", views.knowledge_cancel),
    path("knowledge/<str:knowledge_id>/download", views.knowledge_download),
    path("knowledge/<str:knowledge_id>/preview", views.knowledge_preview),
    path("knowledge/image/<str:knowledge_id>/<str:chunk_id>", views.generic_action, {"resource_type": "knowledge", "action": "image"}),
    path("chunks/<str:knowledge_id>", views.chunks_collection),
    path("chunks/<str:knowledge_id>/<str:chunk_id>", views.chunks_collection),
    path("chunks/by-id/<str:chunk_id>", views.chunks_collection),
    path("chunks/by-id/<str:chunk_id>/questions", views.chunks_collection),
    path("sessions", views.sessions_collection),
    path("sessions/batch", views.sessions_collection),
    path("sessions/<str:session_id>", views.sessions_collection),
    path("sessions/<str:session_id>/messages", views.session_messages_clear),
    path("sessions/<str:session_id>/generate_title", views.session_title),
    path("sessions/<str:session_id>/stop", views.session_stop),
    path("sessions/<str:session_id>/pin", views.session_pin),
    path("sessions/continue-stream/<str:session_id>", views.continue_stream),
    path("knowledge-chat/<str:session_id>", views.chat_endpoint),
    path("agent-chat/<str:session_id>", views.chat_endpoint, {"agent": True}),
    path("knowledge-search", views.knowledge_search_post),
    path("messages/search", views.messages_search),
    path("messages/chat-history-stats", views.chat_history_stats),
    path("messages/<str:session_id>/load", views.messages_load),
    path("messages/<str:session_id>/<str:message_id>", views.message_delete),
    path("models/providers", views.model_providers),
    path("models/usage", views.model_usage),
    path("models", views.models_collection),
    path("models/<str:model_id>", views.models_collection),
    path("models/<str:model_id>/credentials", views.model_credentials),
    path("models/<str:model_id>/credentials/<str:field>", views.model_credentials),
    path("evaluation/", views.generic_action, {"resource_type": "evaluation", "action": "run"}),
    path("initialization/config/<str:kb_id>", views.initialization_config),
    path("initialization/initialize/<str:kb_id>", views.initialization_update),
    path("initialization/config/<str:kb_id>", views.initialization_update),
    path("initialization/ollama/status", views.generic_action, {"resource_type": "ollama", "action": "status"}),
    path("initialization/ollama/models", views.generic_action, {"resource_type": "ollama", "action": "models"}),
    path("initialization/ollama/models/check", views.generic_action, {"resource_type": "ollama", "action": "check"}),
    path("initialization/ollama/models/download", views.generic_action, {"resource_type": "ollama", "action": "download"}),
    path("initialization/ollama/download/progress/<str:task_id>", views.task_progress),
    path("initialization/ollama/download/tasks", views.generic_action, {"resource_type": "ollama", "action": "tasks"}),
    path("initialization/remote/check", views.generic_action, {"resource_type": "models", "action": "remote/check"}),
    path("initialization/embedding/test", views.generic_action, {"resource_type": "models", "action": "embedding/test"}),
    path("initialization/rerank/check", views.generic_action, {"resource_type": "models", "action": "rerank/check"}),
    path("initialization/asr/check", views.generic_action, {"resource_type": "models", "action": "asr/check"}),
    path("initialization/multimodal/test", views.generic_action, {"resource_type": "models", "action": "multimodal/test"}),
    path("initialization/extract/text-relation", views.generic_action, {"resource_type": "extract", "action": "text-relation"}),
    path("initialization/extract/fabri-tag", views.generic_action, {"resource_type": "extract", "action": "fabri-tag"}),
    path("initialization/extract/fabri-text", views.generic_action, {"resource_type": "extract", "action": "fabri-text"}),
    path("system/info", views.system_info),
    path("system/parser-engines", views.parser_engines),
    path("system/parser-engines/check", views.generic_action, {"resource_type": "system", "action": "parser-engines/check"}),
    path("system/docreader/reconnect", views.generic_action, {"resource_type": "system", "action": "docreader"}),
    path("system/storage-engine-status", views.storage_status),
    path("system/storage-engine-check", views.generic_action, {"resource_type": "system", "action": "storage-engine-check"}),
    path("system/admin/promote", views.generic_action, {"resource_type": "system_admin", "action": "promote"}),
    path("system/admin/revoke", views.generic_action, {"resource_type": "system_admin", "action": "revoke"}),
    path("system/admin/list", views.generic_collection, {"resource_type": "system_admins"}),
    path("system/admin/settings", views.generic_collection, {"resource_type": "system_settings"}),
    path("system/admin/settings/<str:item_id>", views.generic_collection, {"resource_type": "system_settings"}),
    path("system/admin/audit-log", views.audit_logs),
    path("mcp-oauth/callback", views.generic_action, {"resource_type": "mcp_oauth", "action": "callback"}),
    path("mcp-services", views.generic_collection, {"resource_type": "mcp_services"}),
    path("mcp-services/<str:item_id>", views.generic_collection, {"resource_type": "mcp_services"}),
    path("mcp-services/<str:item_id>/test", views.generic_action, {"resource_type": "mcp_services", "action": "test"}),
    path("mcp-services/<str:item_id>/tools", views.generic_action, {"resource_type": "mcp_services", "action": "tools"}),
    path("mcp-services/<str:item_id>/resources", views.generic_action, {"resource_type": "mcp_services", "action": "resources"}),
    path("mcp-services/<str:item_id>/credentials", views.generic_action, {"resource_type": "mcp_services", "action": "credentials"}),
    path("mcp-services/<str:item_id>/credentials/<str:sub_id>", views.generic_action, {"resource_type": "mcp_services", "action": "credentials"}),
    path("mcp-services/<str:item_id>/tool-approvals", views.generic_action, {"resource_type": "mcp_services", "action": "tool-approvals"}),
    path("mcp-services/<str:item_id>/tool-approvals/<str:sub_id>", views.generic_action, {"resource_type": "mcp_services", "action": "tool-approvals"}),
    path("mcp-services/<str:item_id>/oauth/authorize-url", views.generic_action, {"resource_type": "mcp_services", "action": "oauth/authorize-url"}),
    path("mcp-services/<str:item_id>/oauth/status", views.generic_action, {"resource_type": "mcp_services", "action": "oauth/status"}),
    path("mcp-services/<str:item_id>/oauth/token", views.generic_action, {"resource_type": "mcp_services", "action": "oauth/token"}),
    path("agent-tools/tool-approvals/<str:item_id>", views.generic_action, {"resource_type": "agent_tools", "action": "tool-approvals"}),
    path("web-search/providers", views.generic_action, {"resource_type": "web_search", "action": "providers"}),
    path("web-search-providers/types", views.generic_action, {"resource_type": "web_search_providers", "action": "types"}),
    path("web-search-providers/test", views.generic_action, {"resource_type": "web_search_providers", "action": "test"}),
    path("web-search-providers", views.generic_collection, {"resource_type": "web_search_providers"}),
    path("web-search-providers/<str:item_id>", views.generic_collection, {"resource_type": "web_search_providers"}),
    path("web-search-providers/<str:item_id>/credentials", views.generic_action, {"resource_type": "web_search_providers", "action": "credentials"}),
    path("web-search-providers/<str:item_id>/credentials/<str:sub_id>", views.generic_action, {"resource_type": "web_search_providers", "action": "credentials"}),
    path("web-search-providers/<str:item_id>/test", views.generic_action, {"resource_type": "web_search_providers", "action": "test"}),
    path("vector-stores/types", views.generic_action, {"resource_type": "vector_stores", "action": "types"}),
    path("vector-stores/test", views.generic_action, {"resource_type": "vector_stores", "action": "test"}),
    path("vector-stores", views.generic_collection, {"resource_type": "vector_stores"}),
    path("vector-stores/<str:item_id>", views.generic_collection, {"resource_type": "vector_stores"}),
    path("vector-stores/<str:item_id>/test", views.generic_action, {"resource_type": "vector_stores", "action": "test"}),
    path("agents/placeholders", views.generic_action, {"resource_type": "agents", "action": "placeholders"}),
    path("agents/type-presets", views.generic_action, {"resource_type": "agents", "action": "type-presets"}),
    path("agents", views.generic_collection, {"resource_type": "agents"}),
    path("agents/<str:item_id>", views.generic_collection, {"resource_type": "agents"}),
    path("agents/<str:item_id>/copy", views.generic_action, {"resource_type": "agents", "action": "copy"}),
    path("agents/<str:item_id>/suggested-questions", views.generic_action, {"resource_type": "agents", "action": "suggested-questions"}),
    path("user-favorites", views.generic_collection, {"resource_type": "user_favorites"}),
    path("user-favorites/<str:item_id>/<str:sub_id>", views.generic_collection, {"resource_type": "user_favorites"}),
    path("skills", views.generic_action, {"resource_type": "skills", "action": "list"}),
    path("agents/<str:item_id>/embed-channels", views.generic_collection, {"resource_type": "embed_channels"}),
    path("embed-channels", views.generic_collection, {"resource_type": "embed_channels"}),
    path("embed-channels/<str:item_id>", views.generic_collection, {"resource_type": "embed_channels"}),
    path("embed-channels/<str:item_id>/rotate-token", views.generic_action, {"resource_type": "embed_channels", "action": "rotate-token"}),
    path("embed-channels/<str:item_id>/preview-session", views.generic_action, {"resource_type": "embed_channels", "action": "preview-session"}),
    path("embed-channels/<str:item_id>/stats", views.generic_action, {"resource_type": "embed_channels", "action": "stats"}),
    path("agents/<str:item_id>/im-channels", views.generic_collection, {"resource_type": "im_channels"}),
    path("im-channels", views.generic_collection, {"resource_type": "im_channels"}),
    path("im-channels/<str:item_id>", views.generic_collection, {"resource_type": "im_channels"}),
    path("im-channels/<str:item_id>/toggle", views.generic_action, {"resource_type": "im_channels", "action": "toggle"}),
    path("im-channels/wechat/qrcode", views.generic_action, {"resource_type": "im_channels", "action": "qrcode"}),
    path("im-channels/wechat/qrcode/status", views.generic_action, {"resource_type": "im_channels", "action": "qrcode-status"}),
    path("data-sources/types", views.generic_action, {"resource_type": "data_sources", "action": "types"}),
    path("data-sources/validate-credentials", views.generic_action, {"resource_type": "data_sources", "action": "validate-credentials"}),
    path("data-sources", views.generic_collection, {"resource_type": "data_sources"}),
    path("data-sources/logs/<str:item_id>", views.generic_collection, {"resource_type": "sync_logs"}),
    path("data-sources/<str:item_id>", views.generic_collection, {"resource_type": "data_sources"}),
    path("data-sources/<str:item_id>/<str:action>", views.generic_action, {"resource_type": "data_sources"}),
    path("data-sources/<str:item_id>/credentials/<str:sub_id>", views.generic_action, {"resource_type": "data_sources", "action": "credentials"}),
    path("weknoracloud/credentials", views.generic_action, {"resource_type": "weknoracloud", "action": "credentials"}),
    path("models/weknoracloud/status", views.generic_action, {"resource_type": "weknoracloud", "action": "status"}),
    path("knowledge-bases/<str:kb_id>/wiki/pages", views.wiki_pages),
    re_path(r"^knowledge-bases/(?P<kb_id>[^/]+)/wiki/pages/(?P<slug>.*)$", views.wiki_pages),
    path("knowledge-bases/<str:kb_id>/wiki/move-page", views.generic_action, {"resource_type": "wiki", "action": "move-page"}),
    path("knowledge-bases/<str:kb_id>/wiki/folders", views.wiki_folders),
    path("knowledge-bases/<str:kb_id>/wiki/folders/<str:folder_id>", views.wiki_folders),
    path("knowledge-bases/<str:kb_id>/wiki/index", views.wiki_index),
    path("knowledge-bases/<str:kb_id>/wiki/log", views.wiki_log),
    path("knowledge-bases/<str:kb_id>/wiki/graph", views.wiki_graph),
    path("knowledge-bases/<str:kb_id>/wiki/stats", views.wiki_stats),
    path("knowledge-bases/<str:kb_id>/wiki/search", views.wiki_search),
    path("knowledge-bases/<str:kb_id>/wiki/rebuild-links", views.generic_action, {"resource_type": "wiki", "action": "rebuild-links"}),
    path("knowledge-bases/<str:kb_id>/wiki/lint", views.wiki_lint),
    path("knowledge-bases/<str:kb_id>/wiki/auto-fix", views.generic_action, {"resource_type": "wiki", "action": "auto-fix"}),
    path("knowledge-bases/<str:kb_id>/wiki/issues", views.wiki_issues),
    path("knowledge-bases/<str:kb_id>/wiki/issues/<str:issue_id>/status", views.wiki_issues),
    path("knowledgebase/<str:kb_id>/wiki/pages", views.wiki_pages),
    re_path(r"^knowledgebase/(?P<kb_id>[^/]+)/wiki/pages/(?P<slug>.*)$", views.wiki_pages),
    path("knowledgebase/<str:kb_id>/wiki/move-page", views.generic_action, {"resource_type": "wiki", "action": "move-page"}),
    path("knowledgebase/<str:kb_id>/wiki/folders", views.wiki_folders),
    path("knowledgebase/<str:kb_id>/wiki/folders/<str:folder_id>", views.wiki_folders),
    path("knowledgebase/<str:kb_id>/wiki/index", views.wiki_index),
    path("knowledgebase/<str:kb_id>/wiki/log", views.wiki_log),
    path("knowledgebase/<str:kb_id>/wiki/graph", views.wiki_graph),
    path("knowledgebase/<str:kb_id>/wiki/stats", views.wiki_stats),
    path("knowledgebase/<str:kb_id>/wiki/search", views.wiki_search),
    path("knowledgebase/<str:kb_id>/wiki/rebuild-links", views.generic_action, {"resource_type": "wiki", "action": "rebuild-links"}),
    path("knowledgebase/<str:kb_id>/wiki/lint", views.wiki_lint),
    path("knowledgebase/<str:kb_id>/wiki/auto-fix", views.generic_action, {"resource_type": "wiki", "action": "auto-fix"}),
    path("knowledgebase/<str:kb_id>/wiki/issues", views.wiki_issues),
    path("knowledgebase/<str:kb_id>/wiki/issues/<str:issue_id>/status", views.wiki_issues),
    path("chunker/preview", views.generic_action, {"resource_type": "chunker", "action": "preview"}),
    path("embed/<str:channel_id>/exchange", views.embed_public, {"action": "exchange"}),
    path("embed/<str:channel_id>/config", views.embed_public, {"action": "config"}),
    path("embed/<str:channel_id>/suggested-questions", views.embed_public, {"action": "suggested-questions"}),
    path("embed/<str:channel_id>/chunks/<str:chunk_id>", views.embed_public, {"action": "chunks"}),
    path("embed/<str:channel_id>/sessions", views.embed_public, {"action": "sessions"}),
    path("embed/<str:channel_id>/knowledge-chat/<str:session_id>", views.embed_public, {"action": "knowledge-chat"}),
    path("embed/<str:channel_id>/agent-chat/<str:session_id>", views.embed_public, {"action": "agent-chat"}),
    path("embed/<str:channel_id>/messages/<str:session_id>/load", views.embed_public, {"action": "messages"}),
    path("embed/<str:channel_id>/sessions/<str:session_id>/stop", views.embed_public, {"action": "stop"}),
    path("embed/<str:channel_id>/sessions/<str:session_id>/events", views.embed_public, {"action": "events"}),
]
