# Generated by Django 5.2.15 on 2026-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0002_remove_share_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="content_family",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="detected_mime",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="inspection_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="is_binary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="last_inspected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
