# Generated by Django 5.2.15 on 2026-06-23 09:01

import django.db.models.deletion
import personal_knowledge_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("type", models.CharField(default="document", max_length=32)),
                ("chunking_config", models.JSONField(default=dict)),
                ("image_processing_config", models.JSONField(default=dict)),
                (
                    "embedding_model_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "summary_model_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("cos_config", models.JSONField(default=dict)),
                ("storage_provider_config", models.JSONField(blank=True, null=True)),
                ("vlm_config", models.JSONField(default=dict)),
                ("asr_config", models.JSONField(blank=True, null=True)),
                ("extract_config", models.JSONField(blank=True, null=True)),
                ("faq_config", models.JSONField(blank=True, null=True)),
                ("question_generation_config", models.JSONField(blank=True, null=True)),
                ("wiki_config", models.JSONField(blank=True, null=True)),
                ("indexing_strategy", models.JSONField(default=dict)),
                ("is_temporary", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vector_store_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                ("creator_id", models.CharField(blank=True, default="", max_length=36)),
            ],
            options={
                "db_table": "knowledge_bases",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "knowledge_base_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                ("max_rounds", models.IntegerField(default=5)),
                ("enable_rewrite", models.BooleanField(default=True)),
                (
                    "fallback_strategy",
                    models.CharField(default="fixed", max_length=255),
                ),
                (
                    "fallback_response",
                    models.TextField(default="很抱歉，我暂时无法回答这个问题。"),
                ),
                ("keyword_threshold", models.FloatField(default=0.5)),
                ("vector_threshold", models.FloatField(default=0.5)),
                (
                    "rerank_model_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("embedding_top_k", models.IntegerField(default=10)),
                ("rerank_top_k", models.IntegerField(default=10)),
                ("rerank_threshold", models.FloatField(default=0.65)),
                (
                    "summary_model_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("summary_parameters", models.JSONField(default=dict)),
                ("agent_config", models.JSONField(blank=True, null=True)),
                ("context_config", models.JSONField(blank=True, null=True)),
                ("agent_id", models.CharField(blank=True, default="", max_length=36)),
                ("user_id", models.CharField(blank=True, default="", max_length=36)),
                ("is_pinned", models.BooleanField(default=False)),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sessions",
            },
        ),
        migrations.CreateModel(
            name="TaskRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_type", models.CharField(max_length=64)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("progress", models.FloatField(default=0)),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "task_records",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("api_key", models.CharField(max_length=256, unique=True)),
                ("retriever_engines", models.JSONField(default=list)),
                ("status", models.CharField(default="active", max_length=50)),
                ("business", models.CharField(default="default", max_length=255)),
                ("storage_quota", models.BigIntegerField(default=10737418240)),
                ("storage_used", models.BigIntegerField(default=0)),
                ("agent_config", models.JSONField(blank=True, null=True)),
                ("context_config", models.JSONField(blank=True, null=True)),
                ("conversation_config", models.JSONField(blank=True, null=True)),
                ("web_search_config", models.JSONField(blank=True, null=True)),
                ("parser_engine_config", models.JSONField(blank=True, null=True)),
                ("storage_engine_config", models.JSONField(blank=True, null=True)),
                ("credentials", models.JSONField(blank=True, null=True)),
                ("chat_history_config", models.JSONField(blank=True, null=True)),
                ("retrieval_config", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "tenants",
            },
        ),
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("source", models.CharField(max_length=2048)),
                ("parse_status", models.CharField(default="pending", max_length=50)),
                ("enable_status", models.CharField(default="enabled", max_length=50)),
                (
                    "embedding_model_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("file_type", models.CharField(blank=True, default="", max_length=50)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_path", models.TextField(blank=True, default="")),
                ("file_hash", models.CharField(blank=True, default="", max_length=64)),
                ("storage_size", models.BigIntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("tag_id", models.CharField(blank=True, default="", max_length=36)),
                ("summary_status", models.CharField(default="none", max_length=32)),
                ("pending_subtasks_count", models.IntegerField(default=0)),
                ("last_faq_import_result", models.JSONField(blank=True, null=True)),
                ("channel", models.CharField(default="web", max_length=50)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "knowledges",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.CharField(max_length=36)),
                ("role", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("rendered_content", models.TextField(blank=True, default="")),
                ("knowledge_references", models.JSONField(default=list)),
                ("agent_steps", models.JSONField(blank=True, null=True)),
                ("mentioned_items", models.JSONField(default=list)),
                ("images", models.JSONField(default=list)),
                ("is_completed", models.BooleanField(default=False)),
                ("is_fallback", models.BooleanField(default=False)),
                ("channel", models.CharField(blank=True, default="", max_length=50)),
                ("agent_duration_ms", models.IntegerField(default=0)),
                (
                    "knowledge_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.session",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.AddField(
            model_name="session",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personal_knowledge_base.tenant"
            ),
        ),
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("type", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("parameters", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("is_builtin", models.BooleanField(default=False)),
                ("managed_by", models.CharField(blank=True, default="", max_length=32)),
                ("status", models.CharField(default="active", max_length=50)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "models",
            },
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personal_knowledge_base.tenant"
            ),
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("start_at", models.IntegerField(default=0)),
                ("end_at", models.IntegerField(default=0)),
                (
                    "pre_chunk_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                (
                    "next_chunk_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                ("chunk_type", models.CharField(default="text", max_length=20)),
                (
                    "parent_chunk_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                ("image_info", models.JSONField(blank=True, null=True)),
                ("video_info", models.JSONField(blank=True, null=True)),
                ("relation_chunks", models.JSONField(blank=True, null=True)),
                ("indirect_relation_chunks", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("tag_id", models.CharField(blank=True, default="", max_length=36)),
                ("status", models.IntegerField(default=0)),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("flags", models.IntegerField(default=1)),
                ("seq_id", models.IntegerField(blank=True, null=True)),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.knowledge",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "chunks",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_user_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                ("actor_role", models.CharField(blank=True, default="", max_length=32)),
                ("action", models.CharField(max_length=64)),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_user_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                (
                    "request_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("outcome", models.CharField(default="success", max_length=16)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("avatar", models.CharField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("can_access_all_tenants", models.BooleanField(default=False)),
                ("is_system_admin", models.BooleanField(default=False)),
                ("preferences", models.JSONField(default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.TextField(unique=True)),
                ("token_type", models.CharField(max_length=50)),
                ("expires_at", models.DateTimeField()),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.user",
                    ),
                ),
            ],
            options={
                "db_table": "auth_tokens",
            },
        ),
        migrations.CreateModel(
            name="WikiFolder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("parent_id", models.CharField(blank=True, default="", max_length=36)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "wiki_folders",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("color", models.CharField(blank=True, default="", max_length=32)),
                ("sort_order", models.IntegerField(default=0)),
                ("seq_id", models.IntegerField(blank=True, null=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_tags",
                "unique_together": {("tenant", "knowledge_base", "name")},
            },
        ),
        migrations.CreateModel(
            name="GenericResource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_type", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("data", models.JSONField(default=dict)),
                ("status", models.CharField(default="active", max_length=50)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "generic_resources",
                "indexes": [
                    models.Index(
                        fields=["tenant", "resource_type"],
                        name="generic_res_tenant__d099fc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("role", models.CharField(default="owner", max_length=20)),
                ("status", models.CharField(default="active", max_length=20)),
                ("invited_by", models.CharField(blank=True, default="", max_length=36)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.user",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_members",
                "unique_together": {("user", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(max_length=512)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("source_refs", models.JSONField(default=list)),
                ("page_type", models.CharField(default="page", max_length=32)),
                ("folder_id", models.CharField(blank=True, default="", max_length=36)),
                (
                    "parent_slug",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_knowledge_base.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "wiki_pages",
                "unique_together": {("knowledge_base", "slug")},
            },
        ),
        migrations.RunSQL(
            sql=[
                (
                    """
                    CREATE VIRTUAL TABLE IF NOT EXISTS chunks_fts
                    USING fts5(chunk_id UNINDEXED, tenant_id UNINDEXED, knowledge_base_id UNINDEXED,
                               knowledge_id UNINDEXED, title, content)
                    """
                ),
                "CREATE VIRTUAL TABLE IF NOT EXISTS chunk_embeddings_vec USING vec0(embedding float[384])",
            ],
            reverse_sql=[
                "DROP TABLE IF EXISTS chunks_fts",
                "DROP TABLE IF EXISTS chunk_embeddings_vec",
            ],
        ),
    ]
