# Generated by Django 5.2.15 on 2026-06-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.JSONField(default=list),
        ),
    ]
