# Generated by Django 5.2.15 on 2026-06-23 17:07

import django.db.models.deletion
import personal_knowledge_base.models
from django.db import migrations, models


def clear_legacy_wiki_data(apps, schema_editor):
    WikiPage = apps.get_model("personal_knowledge_base", "WikiPage")
    WikiFolder = apps.get_model("personal_knowledge_base", "WikiFolder")
    WikiPendingOp = apps.get_model("personal_knowledge_base", "WikiPendingOp")
    WikiLogEntry = apps.get_model("personal_knowledge_base", "WikiLogEntry")
    WikiPendingOp.objects.all().delete()
    WikiLogEntry.objects.all().delete()
    WikiPage.objects.all().delete()
    WikiFolder.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("personal_knowledge_base", "0004_remove_manual_url_knowledge"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiLogEntry",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "knowledge_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                ("action", models.CharField(max_length=32)),
                ("doc_title", models.CharField(blank=True, default="", max_length=512)),
                ("summary", models.TextField(blank=True, default="")),
                ("pages_affected", models.JSONField(default=list)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wiki_log_entries",
            },
        ),
        migrations.CreateModel(
            name="WikiPendingOp",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_type", models.CharField(default="wiki:ingest", max_length=64)),
                ("scope", models.CharField(default="knowledge_base", max_length=64)),
                ("scope_id", models.CharField(max_length=64)),
                ("op", models.CharField(max_length=32)),
                ("dedup_key", models.CharField(blank=True, default="", max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("fail_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("enqueued_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "wiki_pending_ops",
            },
        ),
        migrations.AddField(
            model_name="wikifolder",
            name="depth",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wikifolder",
            name="path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="aliases",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="category_path",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="chunk_refs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="depth",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="in_links",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="out_links",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="page_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="status",
            field=models.CharField(default="published", max_length=32),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="wiki_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="title",
            field=models.CharField(max_length=512),
        ),
        migrations.AddIndex(
            model_name="wikifolder",
            index=models.Index(
                fields=["knowledge_base", "parent_id"],
                name="wiki_folders_kb_parent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["knowledge_base", "page_type"], name="wiki_pages_kb_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["knowledge_base", "status"], name="wiki_pages_kb_status_idx"
            ),
        ),
        migrations.AddField(
            model_name="wikilogentry",
            name="knowledge_base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="personal_knowledge_base.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="wikilogentry",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="personal_knowledge_base.tenant",
            ),
        ),
        migrations.AddField(
            model_name="wikipendingop",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="personal_knowledge_base.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="wikilogentry",
            index=models.Index(
                fields=["knowledge_base", "created_at"], name="wiki_log_kb_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikilogentry",
            index=models.Index(fields=["knowledge_id"], name="wiki_log_knowledge_idx"),
        ),
        migrations.AddIndex(
            model_name="wikipendingop",
            index=models.Index(
                fields=["task_type", "scope", "scope_id", "id"],
                name="wiki_pending_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wikipendingop",
            index=models.Index(
                fields=["tenant", "op"], name="wiki_pending_tenant_op_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipendingop",
            index=models.Index(fields=["dedup_key"], name="wiki_pending_dedup_idx"),
        ),
        migrations.RunPython(clear_legacy_wiki_data, migrations.RunPython.noop),
    ]
