# Generated by Django 5.2.15 on 2026-06-27 13:37

import django.db.models.deletion
import personal_knowledge_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_knowledge_base", "0007_deduplicate_active_file_knowledge"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeProcessingSpan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("attempt", models.IntegerField(default=1)),
                (
                    "span_id",
                    models.CharField(
                        default=personal_knowledge_base.models.uuid_str,
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "parent_span_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                ("name", models.CharField(max_length=128)),
                ("kind", models.CharField(default="stage", max_length=16)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_detail", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(default=0)),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_spans",
                        to="personal_knowledge_base.knowledge",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_processing_spans",
                "indexes": [
                    models.Index(
                        fields=["knowledge", "attempt"],
                        name="span_knowledge_attempt_idx",
                    ),
                    models.Index(fields=["parent_span_id"], name="span_parent_idx"),
                ],
            },
        ),
    ]
